hpc <- read.csv("./household_power_consumption.txt", stringsAsFactors=FALSE, header=TRUE, sep=";")
hpc$Date <- as.Date(hpc$Date, format="%d/%m/%Y")
subset_hpc <- subset(hpc, Date >= "2007-02-01" & Date <= "2007-02-02",)
dt <- strptime(paste(subset_hpc$Date, subset_hpc$Time, sep=" "), "%Y-%m-%d %H:%M:%S")
sub1 <- as.numeric(subset_hpc$Sub_metering_1)
sub2 <- as.numeric(subset_hpc$Sub_metering_2)
sub3 <- as.numeric(subset_hpc$Sub_metering_3)

png("plot3.png",height=480, width=480)
plot(dt, sub1, type="l", col="black", ylab="Energy sub metering")
lines(dt,sub2,col="red")
lines(dt,sub3,col="blue")
legend("topright", lty=1, lwd=2, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()