hpc <- read.csv("./household_power_consumption.txt", stringsAsFactors=FALSE, header=TRUE, sep=";")
hpc$Date <- as.Date(hpc$Date, format="%d/%m/%Y")
subset_hpc <- subset(hpc, Date >= "2007-02-01" & Date <= "2007-02-02",)
dt <- strptime(paste(subset_hpc$Date, subset_hpc$Time, sep=" "), "%Y-%m-%d %H:%M:%S")
globalactivepower <- as.numeric(subset_hpc$Global_active_power)
globalreactivepower <- as.numeric(subset_hpc$Global_reactive_power)
sub1 <- as.numeric(subset_hpc$Sub_metering_1)
sub2 <- as.numeric(subset_hpc$Sub_metering_2)
sub3 <- as.numeric(subset_hpc$Sub_metering_3)
vol <- as.numeric(subset_hpc$Voltage)

png("plot4.png", height=480, width=480)
par(mfrow=c(2,2))
plot(dt, globalactivepower, type="l", col="black", ylab="Global Active Power")
plot(dt, vol, type="l", col="black", xlab = "datetime", ylab="Voltage")
plot(dt, sub1, type="l", col="black", ylab="Energy sub metering")
lines(dt, sub2, col="red")
lines(dt, sub3, col="blue")
legend("topright", lty=1, lwd=2, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex=0.75)
plot(dt, globalreactivepower, type="l", col="black", xlab="datetime", ylab="Global_reactive_power")
dev.off()